title: Alfredo J. Bermúdez
display-title: A Strange Path to Becoming a Web Developer
display-sub-title: The Story of Alfredo J. Bermúdez
email: alfredo@ajbermudez.com
description: >
  I'm Alfredo J. Bermúdez, a web developer from Puerto Rico with extensive
  knowledge of <b>HTML</b>, <b>CSS</b> and <b>Javascript</b>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ajbermudez.com" # the base hostname & protocol for your site
github_username:  alfredo-xyz

# Build settings
plugins:
  - octopress-paginate
excerpt_separator: <!--more-->
markdown: kramdown
exclude:
  - '*.scss'
  - '*-init.js'
  - '*.json'
  - node_modules
  - src
  - out
  - README.md
  - webpack.config.js
paginate:
  collection:   posts
  per_page:     5               # maximum number of items per page
  limit:        false           # Maximum number of pages to paginate (false for unlimited)
  permalink:    /page:num/      # pagination path (relative to template page)
  title_suffix: " - page :num"  # Append to template's page title
  category:     ''              # Paginate items in this category
  categories:   []              # Paginate items in any of these categories
  tag:          ''              # Paginate items tagged with this tag
  tags:         []              # Paginate items tagged with any of these tags
  reversed:     false           # Reverse the order of the documents

# Site data
menuitems:
  - name: musings
    url: "/blog.html"
    title: Blog
  - name: experience
    url: "/experience.html"
    title: Experience

collections:
  home:
    defaults:
    - values:
        layout: page

isDev: true
version: 1.3
