title: Alfredo J. Bermúdez - Web Developer
display-title: A Strange Path to Becoming a Web Developer
display-sub-title: The Story of Alfredo J. Bermúdez
email: alfredo@ajbermudez.com
description: >
  I'm Alfredo J. Bermúdez, an experienced web developer with a front-end focus based in NYC.
baseurl: ""
url: "http://ajbermudez.com"


# SEO/Meta settings
author: Alfredo J. Bermúdez
twitter:
  username: AlfBerm
github:
  username: alfredo-xyz
seo:
  name: Alfredo J. Bermúdez
  type: Person
social:
  name: Alfredo J. Bermúdez
  links:
    - https://twitter.com/AlfBerm
    - https://www.linkedin.com/in/alfredo-berm%C3%BAdez-61654516/
    - https://github.com/alfredo-xyz

# Build settings
plugins:
  - octopress-paginate
  - jekyll-postfiles
  - jekyll-seo-tag
  - jekyll-email-protect
excerpt_separator: <!--more-->
markdown: kramdown
exclude:
  - '*.scss'
  - '*-init.js'
  - '*.json'
  - node_modules
  - out
  - README.md
  - src
  - webpack.config.js

# Octopress Paginate Settings
paginate:
  collection:   posts
  per_page:     5               # maximum number of items per page
  limit:        false           # Maximum number of pages to paginate (false for unlimited)
  permalink:    /page:num/      # pagination path (relative to template page)
  title_suffix: " - page :num"  # Append to template's page title
  category:     ''              # Paginate items in this category
  categories:   []              # Paginate items in any of these categories
  tag:          ''              # Paginate items tagged with this tag
  tags:         []              # Paginate items tagged with any of these tags
  reversed:     false           # Reverse the order of the documents

# Site data
menuitems:
  - name: experiments
    url: "/blog.html"
    title: Blog
  - name: experience
    url: "/experience.html"
    title: Experience

collections:
  home:
    defaults:
    - values:
        layout: page

isDev: true
version: 1.3
